all:
  children:
    foo:
      hosts:
        example1.com:
        example2.info:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: /Users/skiscontent/.ssh/example.pem
    jobfun:
      children:
        staging:
          hosts:
            jobfun-staging.com:
              ansible_user: ubuntu
              ansible_ssh_private_key_file: /Users/skiscontent/.ssh/jobfun-staging.pem
